New providers and it is now possible to disable conky warnings

diff --git a/ipee b/ipee
--- a/ipee
+++ b/ipee
@@ -1,62 +1,98 @@
 #/bin/sh
 
-HOME_COUNTRY_SHORT="DE"
+HOME_COUNTRY_SHORT="FR"
 
 function usage() {
-    echo "Usage: $1 [-a] [-c] [-s] [-h]"
+    echo "Usage: $1 [-a] [-c] [-s] [-h] [-d|f] [-k|n]"
     echo "-a: Print all -> format: IP (COUNTRY)" 
     echo "-c: Print country info" 
-    echo "-s: Print country info short" 
+    echo "-s: Print country info (short)" 
+    echo "-k: Print conky formatted output (to be used with dzen2)"
+    echo "-n: Print conky formatted output (warning disabled)"
+    echo "-d: Use checkip.dyndns.org"
+    echo "-f: Use ifconfig.me"
     echo "-h: Display this message"
 }
 
 function save() {
     if test $IP; then
-        [[ -z $XDG_DATA_HOME ]] && local XDG_DATA_HOME=~/.local/share
-        echo $IP > $XDG_DATA_HOME/ip
+        [[ -z $XDG_CACHE_HOME ]] && local XDG_CACHE_HOME=~/.cache
+        echo "$IP" > $XDG_CACHE_HOME/ip
     fi
 }
 
-function ip() { 
-    IP=$(curl -s checkip.dyndns.org | sed -e 's/[^:]*: //' -e 's/<.*$//')
-    [[ -z "$IP" ]] && { echo -e "Couldn't get your IP !\nPlease check your network configuration. Otherwise, checkip.dyndns.org may be down." >&2; exit 2; }
+function ip() {
+    case "$PROVIDER" in
+        "dyn")
+            IP=$(ip_dyndns)
+            ;;
+        "ifcg")
+            IP=$(ip_ifconfig)
+            ;;
+        *)
+            IP=$(ip_ddg)
+            ;;
+    esac
+}
+
+function _ip_error() {
+    echo -e "Couldn't get your IP !\nPlease check your network configuration. Otherwise, $1 may be down." >&2
+    exit 2
+}
+
+function ip_dyndns() { 
+    if ! curl -s checkip.dyndns.org | sed -e 's/[^:]*: //' -e 's/<.*$//'; then
+        _ip_error dyndns.org
+    fi
+}
+
+function ip_ddg() { 
+    if ! curl -s https://duckduckgo.com/ip | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}'; then
+        _ip_error duckduckgo.com
+    fi
+}
+
+function ip_ifconfig() { 
+    if ! curl -s http://ifconfig.me; then 
+        _ip_error duckduckgo.com
+    fi
 }
 
 function country() {
-    test $IP || ip 
     geoiplookup $IP | awk '{ print $5 }'
 }
 
 function country_short() {
-    test $IP || ip
     geoiplookup $IP | awk '{ print $4 }' | sed 's/\(.*\),/\1/'
 }
 
 function print_ip() {
-    ip 
     echo $IP
 }
 
 function print_short() {
-    ip
-    echo "$IP ($(country_short))" 
+    echo "$(ip) ($(country_short))" 
 }
 
 function print_conky() {
-    ip
     local country=$(country_short) country_color
-    [[ "$country" == "$HOME_COUNTRY_SHORT" ]] && { country_color="^fg(red)"; echo -n "$country_color^i(/home/pschmitt/pictures/icons/xbm8x8/info_03.xbm) "; }
+    if [[ -z "$NOWARNING" ]]; then
+        if [[ "$country" == "$HOME_COUNTRY_SHORT" ]]; then
+            country_color="^fg(red)"
+            echo -n "$country_color^i(/home/pschmitt/pictures/icons/xbm8x8/info_03.xbm) "
+        fi
+    fi
     echo "^fg()$IP ($country_color$(country_short)^fg())" 
 }
 
 function print_all() {
-    ip
     echo "$IP ($(country))"
 }
 
-[[ $# -eq 0 ]] && ACTION=default
+ACTION=default
+PROVIDER=ddg
 
-while getopts ':ackhsw-' OPTION; do
+while getopts ':acdfnkhsw-' OPTION; do
     case "$OPTION" in
         a)
             ACTION=all
@@ -64,6 +100,19 @@ while getopts ':ackhsw-' OPTION; do
         c)
             ACTION=country
             ;;
+        d)
+            PROVIDER=dyn 
+            ;;
+        f)
+            PROVIDER=ifcg
+            ;;
+        h)
+            usage $(basename $0)
+            exit 0
+            ;;
+        n)
+            NOWARNING=1
+            ;&
         k)
             ACTION=conky
             ;;
@@ -74,10 +123,14 @@ while getopts ':ackhsw-' OPTION; do
             ACTION=warn
             ;;
         ?)
+            echo -e "Unkown option -$OPTARG\n" >&2 
             usage $(basename $0)
+            exit 1
             ;;
     esac
 done
+
+ip
 
 case "$ACTION" in
     default)
